name: Release

on:
  repository_dispatch:
    types: [gmedit-plugin-push]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create revision'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: echo "Getting release ${{ github.event.client_payload.tag }}"
    - run: mkdir -p zip
    - name: Download GMEdit Plugin
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "Rivals-Workshop-Community-Projects/rivals-workshop-assistant-gmedit"
        version: "tags/${{ github.event.client_payload.tag }}"
        file: "rivals-workshop-assistant.zip"
        target: "zip/gmedit-plugin.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Decompress GMEdit Plugin
      uses: TonyBogdanov/zip@1.0
      with:
          args: unzip -qq ./zip/gmedit-plugin.zip -d ./plugins

    # Make release dir
    - run: mkdir -p release
    # Copy source into release dir
    - run: rsync -a --exclude='.*' --exclude='release' --exclude='zip' . release/gmedit
    - uses: papeloto/action-zip@v1
      with:
        files: release/
        dest: release/GMEdit-rivals-config.zip

    - uses: actions/upload-artifact@v1
      with:
        name: zip_preview
        path: release/GMEdit-rivals-config.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "release/GMEdit-rivals-config.zip"
        tag_name: ${{ github.event.client_payload.tag }}
